spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  cache:
    type: simple